### ISSUE TITLE
help with website

### ISSUE THREAD

**Issue by nicolevasilevsky** [OHSULibrary-DataScienceInstitute/OHSULibrary-DataScienceInstitute.github.io#1]
Tracking all my issues in this ticket to ask @rchampieux for help
- [x] update favicon
- [x] need to add a link to the registration form, related to https://github.com/OHSU-Library/DataScienceInstitute/issues/8, (registration form is [here](https://docs.google.com/forms/d/e/1FAIpQLSeslJLf35fn1xNlrGRe5Ia1KCnsPve5RLw8NKpckmdZhQ9t0g/viewform))
- [x] add a link to registration on the top tool bar
- [x] Come say hi page- do we want to link to a github repo? And do we want to create a mailing list (like via google groups)? (https://github.com/OHSU-Library/DataScienceInstitute/issues/16)
- [x] need to update lessons page, we should update this with the material from the actual ODSI, but there is a lot of useful content on here that maybe we can reuse?
- [x] Resources - we should update this to be more specific for ODSI, but I think there is a lot of good content here that we can reuse
- [x] reformat the schedule table?
- [x] change the name of each section - currently the schedule section is called 'events', see https://ohsulibrary-datascienceinstitute.github.io/#events. We can change this to 'schedule', but I am scared to do it because it needs to be changed in a lot of places. If we change this, it needs to be changed on the registration form too.
- [x] I removed the title OHSU Data Science Institute from the top (in the config file), but let me know if you'd like to add it back. I thought it would be nice if we could use the horizontal logo across the top, but when I added it, it was super tiny and I don't know how to make it bigger.
- [x] link to code of conduct is broken (note, it is broken on the Bio Data Club website too)
- [x] merge repos

**Comment by nicolevasilevsky** [comment]
- [x] need to rename all the text from OHSU Data Science... to OHSU Library Data Science...

**Comment by nicolevasilevsky** [comment]
- [x] add DSI logo to the registration form

**Comment by nicolevasilevsky** [comment]
- [x] add logos to github repo

**Comment by nicolevasilevsky** [comment]
- [x] @rchampieux need to create an email list and add it to the email link in the 'come say hi' section

**Comment by nicolevasilevsky** [comment]
- [ ] need to either make wider columns in the table or wrap the text, the text is appearing to run together (see last line in table). I don't know how to fix this, @rchampieux can you fix it?

**Comment by rchampieux** [comment]
@nicolevasilevsky for now I deleted the "Lessons" link from the nav bar (though the BioData Club lessons page still exists in this repo).  We can update this with our session course content once we have this. 

Additionally, rather than trying to integrate the BioData Club lesson content in our site, I think we should just point to them as a good resource and people can browse their lessons from there.

**Comment by nicolevasilevsky** [comment]
@rchampieux sounds good! thank you!
