### ISSUE TITLE
fix spacing for the contact us section

### ISSUE THREAD

**Issue by nicolevasilevsky** [OHSULibrary-DataScienceInstitute/OHSULibrary-DataScienceInstitute.github.io#6]
The spacing is really weird in the 'contact us' section, could we decrease the amount of space between the text and the button?

![image](https://user-images.githubusercontent.com/6722114/28549148-15d73a06-708d-11e7-80b4-595a7303aaab.png)

**Comment by rchampieux** [comment]
Strange - it wasn't like this previously.  Where updates made since last Thursday that may have caused this @nicolevasilevsky?  I will look into this, but can't get to it until Thursday or Friday.

**Comment by nicolevasilevsky** [comment]
I'm not sure what causes the weird spacing. But yes, it wasn't like that before.

**Comment by rchampieux** [comment]
Did you make any updates (even if they seem unrelated) to content that appears in this area - this will help me figure out where to start.

**Comment by nicolevasilevsky** [comment]
oh yes, I did! I added the email address. I wonder if that affected it? Honestly, I didn't notice if was spaced weirdly before or after I did that - sorry!

**Comment by rchampieux** [comment]
Haha!  No worries, it's Github not you.  That helps.  I'll take a look and fix asap.
